services:
  mysql:
    image: mysql:8.0
    container_name: livraria-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: livraria
    ports:
      - "3306:3306"
    volumes:
      - livraria-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  livraria-mysql-data:
