api.excecaoPermissao = Voc� n�o tem permiss�o para acessar este recurso
api.excecao = Foi gerada uma exce��o

api.livro = Livro API
api.livro.description = Endpoint para criar, atualizar, deletar, excluir e buscar os Livro.
api.livro.listar = Listar livros
api.livro.salvar = Criar um livro
api.livro.editar = Editar um livro
api.livro.excluir = Excluir um livro por id
api.livro.obterId = Obter detalhes de um livro pelo id
api.livro.buscarTitulo = Buscar livro por t�tulo 
api.livro.buscarAutor = Buscar livro por autor
api.livro.retorno = Retorna a lista de livro
api.livro.gerarPDF = Gerar pdf

livro.id = C�digo do livro
livro.isbn = Isbn do livro
livro.autor = Autor do livro
livro.titulo = T�tulo do livro
livro.preco = Pre�o do livro
livro.dataPublicacao = Data da publica��o do livro
livro.imagemCapa = Imagem da capa do livro

role.id = C�digo da role
role.descricao = Descri��o da role

api.usuario = Usu�rio API
api.usuario.description = Endpoint para criar, atualizar, deletar, excluir e buscar o Usu�rio.
api.usuario.listar = Listar usu�rios
api.usuario.salvar = Criar um usu�rio
api.usuario.editar = Editar um usu�rio
api.usuario.excluir = Excluir um usu�rio por id
api.usuario.obterId = Obter detalhes de um usu�rio pelo id
api.usuario.buscarNome = Buscar usu�rio por nome 
api.usuario.buscarEmail = Buscar usu�rio por email
api.usuario.buscarRole = Buscar usu�rio por perfil
api.usuario.listarRoles = Listar roles
api.usuario.fazerTraducao = Fazer tradu��o
api.usuario.gerarPDF = Gerar pdf

usuario.id = C�digo do usu�rio
usuario.nome = Nome do usu�rio
usuario.email = Email do usu�rio
usuario.senha = Senha do usu�rio

api.upload = Upload API
api.upload.description = Endpoint para upload de arquivos.
api.upload.imagem = Fazer upload de uma imagem

api.role = Perfil API
api.role.description = Endpoint para criar, atualizar, deletar, excluir e buscar o Perfil.
api.role.listar = Listar perfis
api.role.salvar = Criar um perfil
api.role.editar = Editar um perfil
api.role.excluir = Excluir um perfil por id
api.role.obterId = Obter detalhes de um perfil pelo id